website_1: https://test-stand.gb.ru/gateway/login
website_2: https://test-stand.gb.ru/api/posts
website_3: https://test-stand.gb.ru/gateway/posts
search_title : Test title
username: Batruha
password: efad7cc6ce
post_title: It's a new post
post_description: test post
post_content: There some text

